// apps/www/src/components/section-title/section-title.tsx
import classnames from 'classnames'
import s from './section-title.module.scss'

import type { SectionTitleProps } from "./types";

const SectionTitle = ({
  title,
  subtitle,
  background,
  alignment = 'left',
  className,
  hasBorder = true,
  children,
}: SectionTitleProps) => {

  const classes = classnames([
    s.root,
    s[`alignment--${alignment}`],
    s[`background--${background}`],
    {
      [s[`has-border`]]: hasBorder
    },
    className,
  ])

  return (
    <div className={classes}>
      {title}
      {subtitle}
      {children}
    </div>
  )
}

export { SectionTitle }
export type { SectionTitleProps };

// packages/cadence-core-web-components/src/components/section-title/section-title.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { sectionTitleStyles } from './section-title.styles';
import type { SectionTitleAlignment, SectionTitleBackground } from './types';

@customElement('cds-section-title')
export class CdsSectionTitle extends LitElement {
  static styles = [sectionTitleStyles];

  @property({ reflect: true })
  alignment: SectionTitleAlignment = 'left';

  @property({ reflect: true })
  background?: SectionTitleBackground;

  @property({ type: Boolean, attribute: 'has-border', reflect: true })
  hasBorder = true;

  render() {
    return html`
      <slot name="title"></slot>
      <slot name="subtitle"></slot>
      <slot></slot>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cds-section-title': CdsSectionTitle;
  }
}
