// packages/cadence-core-web-components/src/components/flex/flex.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { flexStyles } from './flex.styles';
import type {
  FlexDirection,
  FlexGap,
  FlexPadding,
  FlexAlign,
  FlexJustify,
  FlexBackground,
} from './types';

@customElement('cds-flex')
export class CdsFlex extends LitElement {
  static styles = [flexStyles];

  @property({ reflect: true })
  direction: FlexDirection = 'column';

  @property({ reflect: true })
  gap: FlexGap = 'none';

  @property({ reflect: true })
  padding: FlexPadding = 'none';

  @property({ attribute: 'align-items', reflect: true })
  alignItems?: FlexAlign;

  @property({ attribute: 'align-content', reflect: true })
  alignContent?: FlexAlign;

  @property({ attribute: 'justify-content', reflect: true })
  justifyContent?: FlexJustify;

  @property({ type: Boolean, reflect: true })
  wrap = false;

  @property({ reflect: true })
  background?: FlexBackground;

  render() {
    return html`<slot></slot>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cds-flex': CdsFlex;
  }
}

// apps/www/src/app/components/flex/flex.tsx
import classnames from 'classnames'
import s from './flex.module.scss'

import type { FlexProps } from './types'

const Flex = ({
  children,
  tag = 'div',
  gap = 'none',
  padding = 'none',
  direction = 'column',
  className,
  alignItems,
  alignContent,
  justifyItems,
  justifyContent,
  background,
  wrap,
}: FlexProps) => {

  const classes = classnames([
    s.root,
    s[`gap--${gap}`],
    s[`padding--${padding}`],
    s[direction],
    s[`align-items--${alignItems}`],
    s[`align-content--${alignContent}`],
    s[`justify-items--${justifyItems}`],
    s[`justify--${justifyContent}`],
    s[wrap ? `wrap` : null],
    className,
  ])

  const Tag = tag;

  return (
    <Tag className={classes}>{children}</Tag>
  )
}

export { Flex }
export type { FlexProps }
