// packages/cadence-core-web-components/src/components/blockquote/blockquote.ts
import { LitElement, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { blockquoteStyles } from './blockquote.styles';
import '../text/text';
import '../link/link';

@customElement('cds-blockquote')
export class CdsBlockquote extends LitElement {
  static styles = [blockquoteStyles];

  @property()
  attribution?: string;

  @property()
  link?: string;

  @property({ type: Boolean, reflect: true })
  collapse = false;

  private _renderAttribution() {
    if (!this.attribution) return nothing;

    const attributionText = `– ${this.attribution}`;

    return html`
      <cds-text
        class="attribution"
        tag="p"
        type="expressive-body"
        size="body-small"
        collapse
        data-cy="cds-blockquote-attribution"
      >
        ${this.link
          ? html`<cds-link href=${this.link} type="secondary">${attributionText}</cds-link>`
          : attributionText}
      </cds-text>
    `;
  }

  render() {
    return html`
      <cds-text
        class="quote"
        tag="blockquote"
        type="expressive-body"
        size="body-large"
        collapse
        data-cy="cds-blockquote-quote"
      >
        <em><slot></slot></em>
      </cds-text>
      ${this._renderAttribution()}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cds-blockquote': CdsBlockquote;
  }
}

// apps/www/src/components/blockquote/blockquote.tsx
import classnames from 'classnames'
import { Flex } from '@components/flex'
import { Text } from '@components/text'
import { Link } from '@components/link'
import s from './blockquote.module.scss'

import type { BlockquoteProps } from './types'

const Blockquote = ({
	quote,
	attribution,
	link,
	collapse,
	className,
}: BlockquoteProps) => {
	const classes = classnames([s.root, { [s.collapse]: collapse }, className])

	const renderAttribution = () => {
		if (link !== undefined) {
			return (
				<Text
					tag="p"
					type="expressive-body"
					size="body-small"
					collapse
					dataCy="cds-blockquote-attribution"
				>
					<Link href={link} type="secondary">
						– {attribution}
					</Link>
				</Text>
			)
		} else {
			return (
				<Text
					tag="p"
					type="expressive-body"
					size="body-small"
					collapse
					dataCy="cds-blockquote-attribution"
				>
					– {attribution}
				</Text>
			)
		}
	}

	return (
		<Flex
			tag="div"
			direction="column"
			gap="large"
			className={classes}
			data-cy="cds-blockquote"
		>
			{quote && (
				<Text
					tag="blockquote"
					type="expressive-body"
					size="body-large"
					collapse
				>
					<em data-cy="cds-blockquote-quote">{quote}</em>
				</Text>
			)}
			{renderAttribution()}
		</Flex>
	)
}

export { Blockquote }
export type { BlockquoteProps }
